// Copyright 2019 The eutherum Authors
// This file is part of the eutherum library.
//
// The eutherum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The eutherum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the eutherum library. If not, see <http://www.gnu.org/licenses/>.

// Package checkpointeuracle is a wrapper of checkpoint euracle contract with
// additional rules defined. This package can be used both in LES client or
// server side for offering euracle related APIs.
package checkpointeuracle

import (
	"encoding/binary"
	"sync"
	"sync/atomic"
	"time"

	"github.com/eutherum/eutherum/accounts/abi/bind"
	"github.com/eutherum/eutherum/common"
	"github.com/eutherum/eutherum/contracts/checkpointeuracle"
	"github.com/eutherum/eutherum/crypto"
	"github.com/eutherum/eutherum/log"
	"github.com/eutherum/eutherum/params"
)

// CheckpointEuracle is responsible for offering the latest stable checkpoint
// generated and announced by the contract admins on-chain. The checkpoint can
// be verified by clients locally during the checkpoint syncing.
type CheckpointEuracle struct {
	config   *params.CheckpointEuracleConfig
	contract *checkpointeuracle.CheckpointEuracle

	running  int32                                 // Flag whether the contract backend is set or not
	getLocal func(uint64) params.TrustedCheckpoint // Function used to retrieve local checkpoint

	checkMu              sync.Mutex                // Mutex to sync access to the fields below
	lastCheckTime        time.Time                 // Time we last checked the checkpoint
	lastCheckPoint       *params.TrustedCheckpoint // The last stable checkpoint
	lastCheckPointHeight uint64                    // The height of last stable checkpoint
}

// New creates a checkpoint euracle handler with given configs and callback.
func New(config *params.CheckpointEuracleConfig, getLocal func(uint64) params.TrustedCheckpoint) *CheckpointEuracle {
	return &CheckpointEuracle{
		config:   config,
		getLocal: getLocal,
	}
}

// Start binds the contract backend, initializes the euracle instance
// and marks the status as available.
func (euracle *CheckpointEuracle) Start(backend bind.ContractBackend) {
	contract, err := checkpointeuracle.NewCheckpointEuracle(euracle.config.Address, backend)
	if err != nil {
		log.Error("Euracle contract binding failed", "err", err)
		return
	}
	if !atomic.CompareAndSwapInt32(&euracle.running, 0, 1) {
		log.Error("Already bound and listening to registrar")
		return
	}
	euracle.contract = contract
}

// IsRunning returns an indicator whether the euracle is running.
func (euracle *CheckpointEuracle) IsRunning() bool {
	return atomic.LoadInt32(&euracle.running) == 1
}

// Contract returns the underlying raw checkpoint euracle contract.
func (euracle *CheckpointEuracle) Contract() *checkpointeuracle.CheckpointEuracle {
	return euracle.contract
}

// StableCheckpoint returns the stable checkpoint which was generated by local
// indexers and announced by trusted signers.
func (euracle *CheckpointEuracle) StableCheckpoint() (*params.TrustedCheckpoint, uint64) {
	euracle.checkMu.Lock()
	defer euracle.checkMu.Unlock()
	if time.Since(euracle.lastCheckTime) < 1*time.Minute {
		return euracle.lastCheckPoint, euracle.lastCheckPointHeight
	}
	// Look it up properly
	// Retrieve the latest checkpoint from the contract, abort if empty
	latest, hash, height, err := euracle.contract.Contract().GetLatestCheckpoint(nil)
	euracle.lastCheckTime = time.Now()
	if err != nil || (latest == 0 && hash == [32]byte{}) {
		euracle.lastCheckPointHeight = 0
		euracle.lastCheckPoint = nil
		return euracle.lastCheckPoint, euracle.lastCheckPointHeight
	}
	local := euracle.getLocal(latest)

	// The following scenarios may occur:
	//
	// * local node is out of sync so that it doesn't have the
	//   checkpoint which registered in the contract.
	// * local checkpoint doesn't match with the registered one.
	//
	// In both cases, no stable checkpoint will be returned.
	if local.HashEqual(hash) {
		euracle.lastCheckPointHeight = height.Uint64()
		euracle.lastCheckPoint = &local
		return euracle.lastCheckPoint, euracle.lastCheckPointHeight
	}
	return nil, 0
}

// VerifySigners recovers the signer addresses according to the signature and
// checks whether there are enough approvals to finalize the checkpoint.
func (euracle *CheckpointEuracle) VerifySigners(index uint64, hash [32]byte, signatures [][]byte) (bool, []common.Address) {
	// Short circuit if the given signatures doesn't reach the threshold.
	if len(signatures) < int(euracle.config.Threshold) {
		return false, nil
	}
	var (
		signers []common.Address
		checked = make(map[common.Address]struct{})
	)
	for i := 0; i < len(signatures); i++ {
		if len(signatures[i]) != 65 {
			continue
		}
		// EIP 191 style signatures
		//
		// Arguments when calculating hash to validate
		// 1: byte(0x19) - the initial 0x19 byte
		// 2: byte(0) - the version byte (data with intended validator)
		// 3: this - the validator address
		// --  Application specific data
		// 4 : checkpoint section_index (uint64)
		// 5 : checkpoint hash (bytes32)
		//     hash = keccak256(checkpoint_index, section_head, cht_root, bloom_root)
		buf := make([]byte, 8)
		binary.BigEndian.PutUint64(buf, index)
		data := append([]byte{0x19, 0x00}, append(euracle.config.Address.Bytes(), append(buf, hash[:]...)...)...)
		signatures[i][64] -= 27 // Transform V from 27/28 to 0/1 according to the yellow paper for verification.
		pubkey, err := crypto.Ecrecover(crypto.Keccak256(data), signatures[i])
		if err != nil {
			return false, nil
		}
		var signer common.Address
		copy(signer[:], crypto.Keccak256(pubkey[1:])[12:])
		if _, exist := checked[signer]; exist {
			continue
		}
		for _, s := range euracle.config.Signers {
			if s == signer {
				signers = append(signers, signer)
				checked[signer] = struct{}{}
			}
		}
	}
	threshold := euracle.config.Threshold
	if uint64(len(signers)) < threshold {
		log.Warn("Not enough signers to approve checkpoint", "signers", len(signers), "threshold", threshold)
		return false, nil
	}
	return true, signers
}
